# Generated by Django 5.0.7 on 2025-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroup",
            name="display_name",
            field=models.CharField(default="Unnamed Group", max_length=128),
        ),
    ]
