# Generated by Django 5.0.7 on 2024-07-20 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_img_objec"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
