# Generated by Django 5.0.7 on 2024-07-20 11:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="img_objec",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True), size=None
            ),
        ),
    ]
